export const USER_DETAIL = 'USER_DETAIL';
export const REMEMBER_ME = 'REMEMBER_ME';
export const AUTH_TOKEN = 'AUTH_TOKEN';
export const RESET_STORE = 'RESET_STORE';
export const MEMBER_DETAIL = 'MEMBER_DETAIL';
export const MEMBER_DATA = 'MEMBER_DATA';
export const FILTER_DATA = 'FILTER_DATA';
export const SEARCH_DATA = 'SEARCH_DATA';
export const CAN_CALL_DIRECTOY_API = 'CAN_CALL_DIRECTOY_API';
export const LOADING = 'LOADING';
export const NOTIFICATION_DETAIL = 'NOTIFICATION_DETAIL';
export const NOTIFICATION_TYPE = 'NOTIFICATION_TYPE';
export const NOTIFICATION_LISTENER_FLAG = 'NOTIFICATION_LISTENER_FLAG';
export const EVENT_INFORMATION = 'EVENT_INFORMATION';
export const EVENT_INFORMATION_FOR_NOTIFICATION = 'EVENT_INFORMATION_FOR_NOTIFICATION';
export const NOTIFICATION_ARRAY_FOR_POP_UP = 'NOTIFICATION_ARRAY_FOR_POP_UP';
export const GET_VOLUNTEER_TASK = 'GET_VOLUNTEER_TASK';
export const GET_TEMPLATE_LIST = 'GET_TEMPLATE_LIST';
export const GET_USER_TEMPLATE_LIST = 'GET_USER_TEMPLATE_LIST';
export const GET_FAMILY_LIST_ARRAY = 'GET_FAMILY_LIST_ARRAY';
export const GET_VOLUNTEER_BOOTH = 'GET_VOLUNTEER_BOOTH';
export const GET_NOT_VOLUNTEER_BOTH = 'GET_NOT_VOLUNTEER_BOTH';
export const GET_BOOTH_WISE_VOTER_LIST = 'GET_BOOTH_WISE_VOTER_LIST';
export const GET_VOLUNTEER_CHANGES = 'GET_VOLUNTEER_CHANGES';
export const SET_ELECTION_LIST = 'SET_ELECTION_LIST';
export const SET_VOLUNTEER_ELECTION_LIST = 'SET_VOLUNTEER_ELECTION_LIST';
export const SET_NOT_VOLUNTEER_ELECTION_LIST = 'SET_NOT_VOLUNTEER_ELECTION_LIST';
export const SET_VOTER_WHO_DOES_NOT_VOTE = 'SET_VOTER_WHO_DOES_NOT_VOTE';
export const SET_VOTER_WHO_DOES_VOTE = 'SET_VOTER_WHO_DOES_VOTE';
export const SET_ALL_ELECTION_LIST = 'SET_ALL_ELECTION_LIST';
export const GET_SURVEY_LIST = 'GET_SURVEY_LIST';
export const SURVEY_VOTER_LIST = 'SURVEY_VOTER_LIST';
export const SET_CURRENT_DRAWER_INDEX = 'SET_CURRENT_DRAWER_INDEX';











